//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaxiWebApp.Components.Pages.Res {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BaxiWebApp.Components.Pages.Res.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad Direction:.
        /// </summary>
        public static string Ad_Direction {
            get {
                return ResourceManager.GetString("Ad_Direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad type:.
        /// </summary>
        public static string Ad_Type {
            get {
                return ResourceManager.GetString("Ad_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All ads.
        /// </summary>
        public static string All_Ads_PageTitle {
            get {
                return ResourceManager.GetString("All_Ads_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on the title of the column to sort it!.
        /// </summary>
        public static string Click_On_Column {
            get {
                return ResourceManager.GetString("Click_On_Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact me!.
        /// </summary>
        public static string Contact_Me {
            get {
                return ResourceManager.GetString("Contact_Me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete ad.
        /// </summary>
        public static string Delete_Ad {
            get {
                return ResourceManager.GetString("Delete_Ad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can see all of the ads:.
        /// </summary>
        public static string Error_Message_Inactivated {
            get {
                return ResourceManager.GetString("Error_Message_Inactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello Baierbrunn.
        /// </summary>
        public static string Greeting {
            get {
                return ResourceManager.GetString("Greeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of seats:.
        /// </summary>
        public static string Number_Of_Seats {
            get {
                return ResourceManager.GetString("Number_Of_Seats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passenger.
        /// </summary>
        public static string Passenger {
            get {
                return ResourceManager.GetString("Passenger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From/to this address:.
        /// </summary>
        public static string Pick_Up_Location {
            get {
                return ResourceManager.GetString("Pick_Up_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick up date and time:.
        /// </summary>
        public static string PickUp_DateAndTime {
            get {
                return ResourceManager.GetString("PickUp_DateAndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am looking for a:.
        /// </summary>
        public static string Search_Adtype {
            get {
                return ResourceManager.GetString("Search_Adtype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Between the following date and time:.
        /// </summary>
        public static string Search_DateAndTime {
            get {
                return ResourceManager.GetString("Search_DateAndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direction:.
        /// </summary>
        public static string Search_Direction {
            get {
                return ResourceManager.GetString("Search_Direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From / to this address:.
        /// </summary>
        public static string Search_PickUpAddress {
            get {
                return ResourceManager.GetString("Search_PickUpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested number of seats:.
        /// </summary>
        public static string Search_RequestedNumberOfSeats {
            get {
                return ResourceManager.GetString("Search_RequestedNumberOfSeats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show me the ad.
        /// </summary>
        public static string Show_Me_Ad {
            get {
                return ResourceManager.GetString("Show_Me_Ad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specific requests:.
        /// </summary>
        public static string Specific_Requests {
            get {
                return ResourceManager.GetString("Specific_Requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please write here the reason for the deleting this ad:.
        /// </summary>
        public static string Write_Reason_For_Deleting_Ad {
            get {
                return ResourceManager.GetString("Write_Reason_For_Deleting_Ad", resourceCulture);
            }
        }
    }
}
