//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaxiWebApp.Components.Pages.Res {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BaxiWebApp.Components.Pages.Res.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad Direction:.
        /// </summary>
        public static string Ad_direction {
            get {
                return ResourceManager.GetString("Ad_direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad not Found.
        /// </summary>
        public static string Ad_not_found {
            get {
                return ResourceManager.GetString("Ad_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad owner.
        /// </summary>
        public static string Ad_owner {
            get {
                return ResourceManager.GetString("Ad_owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad type:.
        /// </summary>
        public static string Ad_type {
            get {
                return ResourceManager.GetString("Ad_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address....
        /// </summary>
        public static string Address___ {
            get {
                return ResourceManager.GetString("Address...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Ads.
        /// </summary>
        public static string All_ads {
            get {
                return ResourceManager.GetString("All_ads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All chat conversations.
        /// </summary>
        public static string All_chat_conversations {
            get {
                return ResourceManager.GetString("All_chat_conversations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And the possibly matching ads:.
        /// </summary>
        public static string And_the_possibly_matching_ads {
            get {
                return ResourceManager.GetString("And_the_possibly_matching_ads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic.
        /// </summary>
        public static string Arabic {
            get {
                return ResourceManager.GetString("Arabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you already in Baierbrunn?.
        /// </summary>
        public static string Are_you_already_in_baierbrunn {
            get {
                return ResourceManager.GetString("Are_you_already_in_baierbrunn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete it?.
        /// </summary>
        public static string Are_you_sure_you_want_to_delete_it {
            get {
                return ResourceManager.GetString("Are_you_sure_you_want_to_delete_it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete our profile? If you delete it, you cannot reactivate it again!.
        /// </summary>
        public static string Are_you_sure_you_want_to_delete_our_profile_if_you_delete_it_you_cannot_reactivate_it_again {
            get {
                return ResourceManager.GetString("Are_you_sure_you_want_to_delete_our_profile_if_you_delete_it_you_cannot_reactivat" +
                        "e_it_again", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to make this user an admin? It cannot be revoked anymore!.
        /// </summary>
        public static string Are_you_sure_you_want_to_make_this_user_an_admin_it_cannot_be_revoked_anymore {
            get {
                return ResourceManager.GetString("Are_you_sure_you_want_to_make_this_user_an_admin_it_cannot_be_revoked_anymore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to reactivate this user?.
        /// </summary>
        public static string Are_you_sure_you_want_to_reactivate_this_user {
            get {
                return ResourceManager.GetString("Are_you_sure_you_want_to_reactivate_this_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you trying to reach Baierbrunn from the moon?.
        /// </summary>
        public static string Are_you_trying_to_reach_baierbrunn_from_the_moon {
            get {
                return ResourceManager.GetString("Are_you_trying_to_reach_baierbrunn_from_the_moon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to the chat.
        /// </summary>
        public static string Back_to_the_chat {
            get {
                return ResourceManager.GetString("Back_to_the_chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Below you can add some additional data that will make your life easier when creating Ads in the application. This is not mandatory and can be always changed / deleted in your profile!.
        /// </summary>
        public static string Below_you_can_add_some_additional_data_that_will_make_your_life_easier_when_creating_ads_in_the_application_this_is_not_mandatory_and_can_be_always_changed_deleted_in_your_profile {
            get {
                return ResourceManager.GetString("Below_you_can_add_some_additional_data_that_will_make_your_life_easier_when_creat" +
                        "ing_ads_in_the_application_this_is_not_mandatory_and_can_be_always_changed_delet" +
                        "ed_in_your_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Below you can select one of your ads, and find matches :).
        /// </summary>
        public static string Below_you_can_select_one_of_your_ads_and_find_matches {
            get {
                return ResourceManager.GetString("Below_you_can_select_one_of_your_ads_and_find_matches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Between the following date and time:.
        /// </summary>
        public static string Between_the_following_date_and_time {
            get {
                return ResourceManager.GetString("Between_the_following_date_and_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string Change_password {
            get {
                return ResourceManager.GetString("Change_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change status:.
        /// </summary>
        public static string Change_status {
            get {
                return ResourceManager.GetString("Change_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your profile data!.
        /// </summary>
        public static string Change_your_profile_data {
            get {
                return ResourceManager.GetString("Change_your_profile_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat.
        /// </summary>
        public static string Chat {
            get {
                return ResourceManager.GetString("Chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese.
        /// </summary>
        public static string Chinese {
            get {
                return ResourceManager.GetString("Chinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to change your password!.
        /// </summary>
        public static string Click_here_to_change_your_password {
            get {
                return ResourceManager.GetString("Click_here_to_change_your_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to change your profile data!.
        /// </summary>
        public static string Click_here_to_change_your_profile_data {
            get {
                return ResourceManager.GetString("Click_here_to_change_your_profile_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on a chat!.
        /// </summary>
        public static string Click_on_a_chat {
            get {
                return ResourceManager.GetString("Click_on_a_chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on the title of the column to sort it!.
        /// </summary>
        public static string Click_on_the_title_of_the_column_to_sort_it {
            get {
                return ResourceManager.GetString("Click_on_the_title_of_the_column_to_sort_it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm email.
        /// </summary>
        public static string Confirm_email {
            get {
                return ResourceManager.GetString("Confirm_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string Confirm_password {
            get {
                return ResourceManager.GetString("Confirm_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact:.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact me!.
        /// </summary>
        public static string Contact_me {
            get {
                return ResourceManager.GetString("Contact_me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new account..
        /// </summary>
        public static string Create_a_new_account {
            get {
                return ResourceManager.GetString("Create_a_new_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new ad.
        /// </summary>
        public static string Create_a_new_ad {
            get {
                return ResourceManager.GetString("Create_a_new_ad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an ad!.
        /// </summary>
        public static string Create_an_ad {
            get {
                return ResourceManager.GetString("Create_an_ad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivate user!.
        /// </summary>
        public static string Deactivate_user {
            get {
                return ResourceManager.GetString("Deactivate_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear {0}
        ///Your ad has been removed by the admins for reasons: {1}
        ///
        ///Ad:
        ///Ad type: {2}
        ///Ad Direction: {3}
        ///Address: {4}
        ///On {5}
        ///Available seats: {6}
        ///Any specific requests: {7}.
        /// </summary>
        public static string Dear__0__your_ad_has_been_removed_by_the_admins_for_reasons__1__ad_ad_type__2__ad_direction__3__address__4__on__5__available_seats__6__any_specific_requests__7_ {
            get {
                return ResourceManager.GetString("Dear_{0}_your_ad_has_been_removed_by_the_admins_for_reasons_{1}_ad_ad_type_{2}_ad" +
                        "_direction_{3}_address_{4}_on_{5}_available_seats_{6}_any_specific_requests_{7}", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default ad type:.
        /// </summary>
        public static string Default_ad_type {
            get {
                return ResourceManager.GetString("Default_ad_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default data for creating ads:.
        /// </summary>
        public static string Default_data_for_creating_ads {
            get {
                return ResourceManager.GetString("Default_data_for_creating_ads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default pick up / drop off location.
        /// </summary>
        public static string Default_pick_up_drop_off_location {
            get {
                return ResourceManager.GetString("Default_pick_up_drop_off_location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete ad.
        /// </summary>
        public static string Delete_ad {
            get {
                return ResourceManager.GetString("Delete_ad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete conversation.
        /// </summary>
        public static string Delete_conversation {
            get {
                return ResourceManager.GetString("Delete_conversation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete my profile!.
        /// </summary>
        public static string Delete_my_profile {
            get {
                return ResourceManager.GetString("Delete_my_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department:.
        /// </summary>
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direction:.
        /// </summary>
        public static string Direction {
            get {
                return ResourceManager.GetString("Direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver.
        /// </summary>
        public static string Driver {
            get {
                return ResourceManager.GetString("Driver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EHS.
        /// </summary>
        public static string EHS {
            get {
                return ResourceManager.GetString("EHS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email....
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address:.
        /// </summary>
        public static string Email_address {
            get {
                return ResourceManager.GetString("Email_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address contains:.
        /// </summary>
        public static string Email_address_contains {
            get {
                return ResourceManager.GetString("Email_address_contains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name@example.com.
        /// </summary>
        public static string email_example {
            get {
                return ResourceManager.GetString("email_example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email..
        /// </summary>
        public static string Enter_your_email {
            get {
                return ResourceManager.GetString("Enter_your_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error confirming your email..
        /// </summary>
        public static string Error_confirming_your_email {
            get {
                return ResourceManager.GetString("Error_confirming_your_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Invalid login attempt..
        /// </summary>
        public static string Error_invalid_login_attempt {
            get {
                return ResourceManager.GetString("Error_invalid_login_attempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading user with ID {0}.
        /// </summary>
        public static string Error_loading_user_with_ID__0_ {
            get {
                return ResourceManager.GetString("Error_loading_user_with_ID_{0}", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find me ads that could match this ad.
        /// </summary>
        public static string Find_me_ads_that_would_match_this_ad {
            get {
                return ResourceManager.GetString("Find_me_ads_that_would_match_this_ad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find me recommendations!.
        /// </summary>
        public static string Find_me_recommendations {
            get {
                return ResourceManager.GetString("Find_me_recommendations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name:.
        /// </summary>
        public static string First_name {
            get {
                return ResourceManager.GetString("First_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password confirmation.
        /// </summary>
        public static string Forgot_password_confirmation {
            get {
                return ResourceManager.GetString("Forgot_password_confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        public static string Forgot_your_password {
            get {
                return ResourceManager.GetString("Forgot_your_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fragrance Team.
        /// </summary>
        public static string FragranceTeam {
            get {
                return ResourceManager.GetString("FragranceTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        public static string French {
            get {
                return ResourceManager.GetString("French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From:.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From/to this address:.
        /// </summary>
        public static string From_to_this_address {
            get {
                return ResourceManager.GetString("From/to_this_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Baierbrunn.
        /// </summary>
        public static string FromBaierbrunn {
            get {
                return ResourceManager.GetString("FromBaierbrunn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Services.
        /// </summary>
        public static string GeneralServices {
            get {
                return ResourceManager.GetString("GeneralServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        public static string German {
            get {
                return ResourceManager.GetString("German", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give a warning!.
        /// </summary>
        public static string Give_a_warning {
            get {
                return ResourceManager.GetString("Give_a_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give this user admin rights!.
        /// </summary>
        public static string Give_this_user_admin_rights {
            get {
                return ResourceManager.GetString("Give_this_user_admin_rights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back to edit the location!.
        /// </summary>
        public static string Go_back_to_edit_the_location {
            get {
                return ResourceManager.GetString("Go_back_to_edit_the_location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have you seen these ads?.
        /// </summary>
        public static string Have_you_seen_these_ads {
            get {
                return ResourceManager.GetString("Have_you_seen_these_ads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All ads.
        /// </summary>
        public static string Here_you_can_see_all_of_the_ads {
            get {
                return ResourceManager.GetString("Here_you_can_see_all_of_the_ads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you will see the ads that are matching your selected ad..
        /// </summary>
        public static string Here_you_will_see_the_ads_that_are_matching_your_selected_ad {
            get {
                return ResourceManager.GetString("Here_you_will_see_the_ads_that_are_matching_your_selected_ad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am a:.
        /// </summary>
        public static string I_am_a {
            get {
                return ResourceManager.GetString("I_am_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am looking for a:.
        /// </summary>
        public static string I_am_looking_for_a {
            get {
                return ResourceManager.GetString("I_am_looking_for_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I will correct it!.
        /// </summary>
        public static string I_will_correct_it {
            get {
                return ResourceManager.GetString("I_will_correct_it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have the same requests regarding the ride (such as &quot;No smokers Please&quot; or &quot;No loud music&quot; etc...) please write them here:.
        /// </summary>
        public static string If_you_have_the_same_requests_regarding_the_ride_such_as_no_smokers_please_or_no_loud_music_etc_please_write_them_here {
            get {
                return ResourceManager.GetString("If_you_have_the_same_requests_regarding_the_ride_such_as_no_smokers_please_or_no_" +
                        "loud_music_etc_please_write_them_here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In this conversation you are talking to {0} to arrange a ride {1}, from/to {2}, on {3}, including {4} passengers..
        /// </summary>
        public static string In_this_conversation_you_are_talking_to__0__to_arrange_a_ride__1__from_to__2__on__3__including__4__passengers {
            get {
                return ResourceManager.GetString("In_this_conversation_you_are_talking_to_{0}_to_arrange_a_ride_{1}_from_to_{2}_on_" +
                        "{3}_including_{4}_passengers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        public static string Inactive {
            get {
                return ResourceManager.GetString("Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT.
        /// </summary>
        public static string IT {
            get {
                return ResourceManager.GetString("IT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italian.
        /// </summary>
        public static string Italian {
            get {
                return ResourceManager.GetString("Italian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japanese.
        /// </summary>
        public static string Japanese {
            get {
                return ResourceManager.GetString("Japanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korean.
        /// </summary>
        public static string Korean {
            get {
                return ResourceManager.GetString("Korean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laboratories.
        /// </summary>
        public static string Laboratories {
            get {
                return ResourceManager.GetString("Laboratories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name:.
        /// </summary>
        public static string Last_name {
            get {
                return ResourceManager.GetString("Last_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked out.
        /// </summary>
        public static string Locked_out {
            get {
                return ResourceManager.GetString("Locked_out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string Log_in {
            get {
                return ResourceManager.GetString("Log_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looks like the location you wrote is not correct, please, give me a valid address!.
        /// </summary>
        public static string Looks_like_the_location_you_wrote_is_not_correct_please_give_me_a_valid_address {
            get {
                return ResourceManager.GetString("Looks_like_the_location_you_wrote_is_not_correct_please_give_me_a_valid_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looks like there is no route between your location and Baierbrunn!.
        /// </summary>
        public static string Looks_like_there_is_no_route_between_your_location_and_baierbrunn {
            get {
                return ResourceManager.GetString("Looks_like_there_is_no_route_between_your_location_and_baierbrunn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looks like you are lost :) Please navigate back to the chat using the navigation menu on the left!.
        /// </summary>
        public static string Looks_like_you_are_lost_please_navigate_back_to_the_chat_using_the_navigation_menu_on_the_left {
            get {
                return ResourceManager.GetString("Looks_like_you_are_lost_please_navigate_back_to_the_chat_using_the_navigation_men" +
                        "u_on_the_left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looks like your ad is very close to Baierbrunn.
        /// </summary>
        public static string Looks_like_your_ad_is_very_close_to_baierbrunn {
            get {
                return ResourceManager.GetString("Looks_like_your_ad_is_very_close_to_baierbrunn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looks like your ad is very far away from Baierbrunn.
        /// </summary>
        public static string Looks_like_your_ad_is_very_far_away_from_baierbrunn {
            get {
                return ResourceManager.GetString("Looks_like_your_ad_is_very_far_away_from_baierbrunn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance.
        /// </summary>
        public static string Maintenance {
            get {
                return ResourceManager.GetString("Maintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make User an Admin:.
        /// </summary>
        public static string Make_user_an_admin {
            get {
                return ResourceManager.GetString("Make_user_an_admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meaning: you are going in the same direction at the same time, and your pick up location or the route you are taking is close enough to each other.
        /// </summary>
        public static string Meaning_you_are_going_in_the_same_direction_at_the_same_time_and_your_pick_up_location_or_the_route_you_are_taking_is_close_enough_to_each_other {
            get {
                return ResourceManager.GetString("Meaning_you_are_going_in_the_same_direction_at_the_same_time_and_your_pick_up_loc" +
                        "ation_or_the_route_you_are_taking_is_close_enough_to_each_other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message:.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify Ad!.
        /// </summary>
        public static string Modify_ad {
            get {
                return ResourceManager.GetString("Modify_ad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        public static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Ads.
        /// </summary>
        public static string My_ads {
            get {
                return ResourceManager.GetString("My_ads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New conversation.
        /// </summary>
        public static string New_conversation {
            get {
                return ResourceManager.GetString("New_conversation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string New_password {
            get {
                return ResourceManager.GetString("New_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No conversations yet!.
        /// </summary>
        public static string No_conversations_yet {
            get {
                return ResourceManager.GetString("No_conversations_yet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No default type.
        /// </summary>
        public static string No_default_type {
            get {
                return ResourceManager.GetString("No_default_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No notifications for you.
        /// </summary>
        public static string No_notifications_for_you {
            get {
                return ResourceManager.GetString("No_notifications_for_you", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No rating yet.
        /// </summary>
        public static string No_rating_yet {
            get {
                return ResourceManager.GetString("No_rating_yet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No warning yet.
        /// </summary>
        public static string No_warning_yet {
            get {
                return ResourceManager.GetString("No_warning_yet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not mandatory field.
        /// </summary>
        public static string Not_mandatory_field {
            get {
                return ResourceManager.GetString("Not_mandatory_field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications:.
        /// </summary>
        public static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications: if you check this box, you will automatically receive an email notification when another user posts an ad that would be matching your needs: It is less than {0} km away from you and less than {1} hour(s) different,
        ///Or your routes will meet somewhere on the way and could be convenient for both of you..
        /// </summary>
        public static string Notifications_if_you_check_this_box_you_will_automatically_receive_an_email_notification_when_another_user_posts_an_ad_that_would_be_matching_your_needs_it_is_less_than__0__km_away_from_you_and_less_than__1__hour_s_different_or_your_routes_will_meet_somewhere_on_the_way_and_could_be_convenient_for_both_of_you {
            get {
                return ResourceManager.GetString(@"Notifications_if_you_check_this_box_you_will_automatically_receive_an_email_notification_when_another_user_posts_an_ad_that_would_be_matching_your_needs_it_is_less_than_{0}_km_away_from_you_and_less_than_{1}_hour_s_different_or_your_routes_will_meet_somewhere_on_the_way_and_could_be_convenient_for_both_of_you", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of seats:.
        /// </summary>
        public static string Number_of_seats {
            get {
                return ResourceManager.GetString("Number_of_seats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of warnings:.
        /// </summary>
        public static string Number_of_warnings {
            get {
                return ResourceManager.GetString("Number_of_warnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password.
        /// </summary>
        public static string Old_password {
            get {
                return ResourceManager.GetString("Old_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On the map you can specify the exact pick up / drop off location!.
        /// </summary>
        public static string On_the_map_you_can_specify_the_exact_pick_up_drop_off_location {
            get {
                return ResourceManager.GetString("On_the_map_you_can_specify_the_exact_pick_up_drop_off_location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passenger.
        /// </summary>
        public static string Passenger {
            get {
                return ResourceManager.GetString("Passenger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick up date and time:.
        /// </summary>
        public static string Pick_up_date_and_time {
            get {
                return ResourceManager.GetString("Pick_up_date_and_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your email to reset your password..
        /// </summary>
        public static string Please_check_your_email_to_reset_your_password {
            get {
                return ResourceManager.GetString("Please_check_your_email_to_reset_your_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please give me a correct Ad type.
        /// </summary>
        public static string Please_give_me_a_correct_ad_type {
            get {
                return ResourceManager.GetString("Please_give_me_a_correct_ad_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please give me a correct address.
        /// </summary>
        public static string Please_give_me_a_correct_address {
            get {
                return ResourceManager.GetString("Please_give_me_a_correct_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please move the marker to the place where you can stop with your car / wait for your pick up!.
        /// </summary>
        public static string Please_move_the_marker_to_the_place_where_you_can_stop_with_your_car_wait_for_your_pick_up {
            get {
                return ResourceManager.GetString("Please_move_the_marker_to_the_place_where_you_can_stop_with_your_car_wait_for_you" +
                        "r_pick up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select!.
        /// </summary>
        public static string Please_select {
            get {
                return ResourceManager.GetString("Please_select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please write here the reason for the deleting this ad:.
        /// </summary>
        public static string Please_write_here_the_reason_for_deleting_this_ad {
            get {
                return ResourceManager.GetString("Please_write_here_the_reason_for_deleting_this_ad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please write here the reason for the deactivation:.
        /// </summary>
        public static string Please_write_here_the_reason_for_the_deactivation {
            get {
                return ResourceManager.GetString("Please_write_here_the_reason_for_the_deactivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please write here the reason for the report:.
        /// </summary>
        public static string Please_write_here_the_reason_for_the_report {
            get {
                return ResourceManager.GetString("Please_write_here_the_reason_for_the_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please write here the reason for the reporting this ad:.
        /// </summary>
        public static string Please_write_here_the_reason_for_the_reporting_this_ad {
            get {
                return ResourceManager.GetString("Please_write_here_the_reason_for_the_reporting_this_ad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please write here the reason for the warning:.
        /// </summary>
        public static string Please_write_here_the_reason_for_the_warning {
            get {
                return ResourceManager.GetString("Please_write_here_the_reason_for_the_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please write your first message here.
        /// </summary>
        public static string Please_write_your_first_message_here {
            get {
                return ResourceManager.GetString("Please_write_your_first_message_here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portuguese.
        /// </summary>
        public static string Portuguese {
            get {
                return ResourceManager.GetString("Portuguese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferred language:.
        /// </summary>
        public static string Preferred_language {
            get {
                return ResourceManager.GetString("Preferred_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production.
        /// </summary>
        public static string Production {
            get {
                return ResourceManager.GetString("Production", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality Control.
        /// </summary>
        public static string QualityControl {
            get {
                return ResourceManager.GetString("QualityControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating:.
        /// </summary>
        public static string Rating {
            get {
                return ResourceManager.GetString("Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reactivate user!.
        /// </summary>
        public static string Reactivate_user {
            get {
                return ResourceManager.GetString("Reactivate_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommend me Ads.
        /// </summary>
        public static string Recommend_me_ads {
            get {
                return ResourceManager.GetString("Recommend_me_ads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended ads.
        /// </summary>
        public static string Recommended_ads {
            get {
                return ResourceManager.GetString("Recommended_ads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register as a new user.
        /// </summary>
        public static string Register_as_a_new_user {
            get {
                return ResourceManager.GetString("Register_as_a_new_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular User .
        /// </summary>
        public static string Regular {
            get {
                return ResourceManager.GetString("Regular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        public static string Remember_me {
            get {
                return ResourceManager.GetString("Remember_me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report ad!.
        /// </summary>
        public static string Report_ad {
            get {
                return ResourceManager.GetString("Report_ad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report conversation.
        /// </summary>
        public static string Report_conversation {
            get {
                return ResourceManager.GetString("Report_conversation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report this conversations to the admins!.
        /// </summary>
        public static string Report_this_conversations_to_the_admins {
            get {
                return ResourceManager.GetString("Report_this_conversations_to_the_admins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend email confirmation.
        /// </summary>
        public static string Resend_email_confirmation {
            get {
                return ResourceManager.GetString("Resend_email_confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password.
        /// </summary>
        public static string Reset_password {
            get {
                return ResourceManager.GetString("Reset_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password confirmation.
        /// </summary>
        public static string Reset_password_confirmation {
            get {
                return ResourceManager.GetString("Reset_password_confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role:.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian.
        /// </summary>
        public static string Russian {
            get {
                return ResourceManager.GetString("Russian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales.
        /// </summary>
        public static string Sales {
            get {
                return ResourceManager.GetString("Sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the ad:.
        /// </summary>
        public static string Save_the_ad {
            get {
                return ResourceManager.GetString("Save_the_ad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all.
        /// </summary>
        public static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show me all recommendations!.
        /// </summary>
        public static string Show_me_all_recommendations {
            get {
                return ResourceManager.GetString("Show_me_all_recommendations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show me the ad.
        /// </summary>
        public static string Show_me_the_ad {
            get {
                return ResourceManager.GetString("Show_me_the_ad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show me the following users:.
        /// </summary>
        public static string Show_me_the_following_users {
            get {
                return ResourceManager.GetString("Show_me_the_following_users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        public static string Spanish {
            get {
                return ResourceManager.GetString("Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specific requests:.
        /// </summary>
        public static string Specific_requests {
            get {
                return ResourceManager.GetString("Specific_requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status:.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supply Chain.
        /// </summary>
        public static string SupplyChain {
            get {
                return ResourceManager.GetString("SupplyChain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for confirming your email..
        /// </summary>
        public static string Thank_you_for_confirming_your_email {
            get {
                return ResourceManager.GetString("Thank_you_for_confirming_your_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The pick up time you added is in the past! Please go back and correct it.
        /// </summary>
        public static string The_pick_up_time_you_added_is_in_the_past_please_go_back_and_correct_it {
            get {
                return ResourceManager.GetString("The_pick_up_time_you_added_is_in_the_past_please_go_back_and_correct_it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These might be interesting for you: .
        /// </summary>
        public static string These_might_be_interesting_for_you {
            get {
                return ResourceManager.GetString("These_might_be_interesting_for_you", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account has been locked out, please try again later..
        /// </summary>
        public static string This_account_has_been_locked_out_please_try_again_later {
            get {
                return ResourceManager.GetString("This_account_has_been_locked_out_please_try_again_later", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This ad is in the past.
        /// </summary>
        public static string This_ad_is_in_the_past {
            get {
                return ResourceManager.GetString("This_ad_is_in_the_past", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This ad must have been deleted!.
        /// </summary>
        public static string This_ad_must_have_been_deleted {
            get {
                return ResourceManager.GetString("This_ad_must_have_been_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamp:.
        /// </summary>
        public static string Timestamp {
            get {
                return ResourceManager.GetString("Timestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To:.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Baierbrunn.
        /// </summary>
        public static string ToBaierbrunn {
            get {
                return ResourceManager.GetString("ToBaierbrunn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turkish.
        /// </summary>
        public static string Turkish {
            get {
                return ResourceManager.GetString("Turkish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunately there are no ad recommendations for you. Please come back later or turn on the notifications so we can inform you when a matching ad is posted!.
        /// </summary>
        public static string Unfortunately_there_are_no_ad_recommendations_for_you_please_come_back_later_or_turn_on_the_notifications_so_we_can_inform_you_when_a_matching_ad_is_posted {
            get {
                return ResourceManager.GetString("Unfortunately_there_are_no_ad_recommendations_for_you_please_come_back_later_or_t" +
                        "urn_on_the_notifications_so_we_can_inform_you_when_a_matching_ad_is_posted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a local account to log in..
        /// </summary>
        public static string Use_a_local_account_to_log_in {
            get {
                return ResourceManager.GetString("Use_a_local_account_to_log_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use another service to log in..
        /// </summary>
        public static string Use_another_service_to_log_in {
            get {
                return ResourceManager.GetString("Use_another_service_to_log_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use another service to register..
        /// </summary>
        public static string Use_another_service_to_register {
            get {
                return ResourceManager.GetString("Use_another_service_to_register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Management Page.
        /// </summary>
        public static string User_management_page {
            get {
                return ResourceManager.GetString("User_management_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning:.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting to Baierbrunn is something we all rely on - but when train service is disrupted, it can be a real challenge. Baxi offers a smart and reliable solution by connecting drivers and passengers with the same destination. Together, we make the journey smoother, more efficient, and more community-driven. Welcome aboard!.
        /// </summary>
        public static string Welcome_text {
            get {
                return ResourceManager.GetString("Welcome_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello Baierbrunn.
        /// </summary>
        public static string Welcome_to_Baierbrunn {
            get {
                return ResourceManager.GetString("Welcome_to_Baierbrunn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Council.
        /// </summary>
        public static string WorkCouncil {
            get {
                return ResourceManager.GetString("WorkCouncil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes you will get notifications.
        /// </summary>
        public static string Yes_you_will_get_notifications {
            get {
                return ResourceManager.GetString("Yes_you_will_get_notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can see all of the ads:.
        /// </summary>
        public static string You_are_inactivated_this_page_is_not_available_for_you {
            get {
                return ResourceManager.GetString("You_are_inactivated_this_page_is_not_available_for_you", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are logged out now!.
        /// </summary>
        public static string You_are_logged_out_now {
            get {
                return ResourceManager.GetString("You_are_logged_out_now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can add an address or location where you can usually pick up / drop off passengers // where you want to be picked up!.
        /// </summary>
        public static string You_can_add_an_address_or_location_where_you_can_usually_pick_up_drop_off_passengers_where_you_want_to_be_picked_up {
            get {
                return ResourceManager.GetString("You_can_add_an_address_or_location_where_you_can_usually_pick_up_drop_off_passeng" +
                        "ers_where_you_want_to_be_picked_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have any ads :) You can create ads by clicking on Create Ad in the menu!.
        /// </summary>
        public static string You_do_not_have_any_ads_you_can_create_ads_by_clicking_on_Create_Ad_in_the_menu {
            get {
                return ResourceManager.GetString("You_do_not_have_any_ads_you_can_create_ads_by_clicking_on_Create_Ad_in_the_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to select Driver or Passenger!.
        /// </summary>
        public static string You_have_to_select_driver_or_passenger {
            get {
                return ResourceManager.GetString("You_have_to_select_driver_or_passenger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You just received a new message from {0} ! Go and check it out: http://localhost:5049/Chat/{1}.
        /// </summary>
        public static string You_just_received_a_new_message_from__0__Go_and_check_it_out_http_localhost_5049_Chat__1_ {
            get {
                return ResourceManager.GetString("You_just_received_a_new_message_from_{0}_Go_and_check_it_out_http_localhost_5049_" +
                        "Chat_{1}", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You received a new message!.
        /// </summary>
        public static string You_received_a_new_message {
            get {
                return ResourceManager.GetString("You_received_a_new_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Baxi ad is deleted!.
        /// </summary>
        public static string Your_Baxi_ad_is_deleted {
            get {
                return ResourceManager.GetString("Your_Baxi_ad_is_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your default pick up / drop off location on the map:.
        /// </summary>
        public static string Your_default_pick_up_drop_off_location_on_the_map {
            get {
                return ResourceManager.GetString("Your_default_pick_up_drop_off_location_on_the_map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your first message:.
        /// </summary>
        public static string Your_first_message {
            get {
                return ResourceManager.GetString("Your_first_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your original ad:.
        /// </summary>
        public static string Your_original_ad {
            get {
                return ResourceManager.GetString("Your_original_ad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been reset. Please log in.
        /// </summary>
        public static string Your_password_has_been_reset_please_log_in {
            get {
                return ResourceManager.GetString("Your_password_has_been_reset_please_log_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your pick up time is in the past!.
        /// </summary>
        public static string Your_pick_up_time_is_in_the_past {
            get {
                return ResourceManager.GetString("Your_pick_up_time_is_in_the_past", resourceCulture);
            }
        }
    }
}
