//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaxiWebApp.Components.Pages.Res {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BaxiWebApp.Components.Pages.Res.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad Direction:.
        /// </summary>
        public static string Ad_direction {
            get {
                return ResourceManager.GetString("Ad_direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad owner.
        /// </summary>
        public static string Ad_owner {
            get {
                return ResourceManager.GetString("Ad_owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad type:.
        /// </summary>
        public static string Ad_type {
            get {
                return ResourceManager.GetString("Ad_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address....
        /// </summary>
        public static string Address___ {
            get {
                return ResourceManager.GetString("Address...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All chat conversations.
        /// </summary>
        public static string All_chat_conversations {
            get {
                return ResourceManager.GetString("All_chat_conversations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete it?.
        /// </summary>
        public static string Are_you_sure_you_want_to_delete_it {
            get {
                return ResourceManager.GetString("Are_you_sure_you_want_to_delete_it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Between the following date and time:.
        /// </summary>
        public static string Between_the_following_date_and_time {
            get {
                return ResourceManager.GetString("Between_the_following_date_and_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat.
        /// </summary>
        public static string Chat {
            get {
                return ResourceManager.GetString("Chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on a chat!.
        /// </summary>
        public static string Click_on_a_chat {
            get {
                return ResourceManager.GetString("Click_on_a_chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on the title of the column to sort it!.
        /// </summary>
        public static string Click_on_the_title_of_the_column_to_sort_it {
            get {
                return ResourceManager.GetString("Click_on_the_title_of_the_column_to_sort_it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact me!.
        /// </summary>
        public static string Contact_me {
            get {
                return ResourceManager.GetString("Contact_me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete ad.
        /// </summary>
        public static string Delete_ad {
            get {
                return ResourceManager.GetString("Delete_ad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete conversation.
        /// </summary>
        public static string Delete_conversation {
            get {
                return ResourceManager.GetString("Delete_conversation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direction:.
        /// </summary>
        public static string Direction {
            get {
                return ResourceManager.GetString("Direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver.
        /// </summary>
        public static string Driver {
            get {
                return ResourceManager.GetString("Driver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From:.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From/to this address:.
        /// </summary>
        public static string From_to_this_address {
            get {
                return ResourceManager.GetString("From/to_this_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Baierbrunn.
        /// </summary>
        public static string FromBaierbrunn {
            get {
                return ResourceManager.GetString("FromBaierbrunn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have you seen these ads?.
        /// </summary>
        public static string Have_you_seen_these_ads {
            get {
                return ResourceManager.GetString("Have_you_seen_these_ads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All ads.
        /// </summary>
        public static string Here_you_can_see_all_of_the_ads {
            get {
                return ResourceManager.GetString("Here_you_can_see_all_of_the_ads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am looking for a:.
        /// </summary>
        public static string I_am_looking_for_a {
            get {
                return ResourceManager.GetString("I_am_looking_for_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looks like you are lost :) Please navigate back to the chat using the navigation menu on the left!.
        /// </summary>
        public static string Looks_like_you_are_lost_please_navigate_back_to_the_chat_using_the_navigation_menu_on_the_left {
            get {
                return ResourceManager.GetString("Looks_like_you_are_lost_please_navigate_back_to_the_chat_using_the_navigation_men" +
                        "u_on_the_left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message:.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New conversation.
        /// </summary>
        public static string New_conversation {
            get {
                return ResourceManager.GetString("New_conversation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No conversations yet!.
        /// </summary>
        public static string No_conversations_yet {
            get {
                return ResourceManager.GetString("No_conversations_yet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of seats:.
        /// </summary>
        public static string Number_of_seats {
            get {
                return ResourceManager.GetString("Number_of_seats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passenger.
        /// </summary>
        public static string Passenger {
            get {
                return ResourceManager.GetString("Passenger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick up date and time:.
        /// </summary>
        public static string Pick_up_date_and_time {
            get {
                return ResourceManager.GetString("Pick_up_date_and_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please write here the reason for the deleting this ad:.
        /// </summary>
        public static string Please_write_here_the_reason_for_deleting_this_ad {
            get {
                return ResourceManager.GetString("Please_write_here_the_reason_for_deleting_this_ad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please write here the reason for the report:.
        /// </summary>
        public static string Please_write_here_the_reason_for_the_report {
            get {
                return ResourceManager.GetString("Please_write_here_the_reason_for_the_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please write your first message here.
        /// </summary>
        public static string Please_write_your_first_messge_here {
            get {
                return ResourceManager.GetString("Please_write_your_first_messge_here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report conversation.
        /// </summary>
        public static string Report_conversation {
            get {
                return ResourceManager.GetString("Report_conversation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report this conversations to the admins!.
        /// </summary>
        public static string Report_this_conversations_to_the_admins {
            get {
                return ResourceManager.GetString("Report_this_conversations_to_the_admins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all.
        /// </summary>
        public static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show me all recommendations!.
        /// </summary>
        public static string Show_me_all_recommendations {
            get {
                return ResourceManager.GetString("Show_me_all_recommendations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show me the ad.
        /// </summary>
        public static string Show_me_the_ad {
            get {
                return ResourceManager.GetString("Show_me_the_ad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specific requests:.
        /// </summary>
        public static string Specific_requests {
            get {
                return ResourceManager.GetString("Specific_requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These might be interesting for you: .
        /// </summary>
        public static string These_might_be_interesting_for_you {
            get {
                return ResourceManager.GetString("These_might_be_interesting_for_you", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamp:.
        /// </summary>
        public static string Timestamp {
            get {
                return ResourceManager.GetString("Timestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To:.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Baierbrunn.
        /// </summary>
        public static string ToBaierbrunn {
            get {
                return ResourceManager.GetString("ToBaierbrunn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello Baierbrunn.
        /// </summary>
        public static string Welcome_to_Baierbrunn {
            get {
                return ResourceManager.GetString("Welcome_to_Baierbrunn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can see all of the ads:.
        /// </summary>
        public static string You_are_inactivated_this_page_is_not_available_for_you {
            get {
                return ResourceManager.GetString("You_are_inactivated_this_page_is_not_available_for_you", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your first message:.
        /// </summary>
        public static string Your_first_message {
            get {
                return ResourceManager.GetString("Your_first_message", resourceCulture);
            }
        }
    }
}
