<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="Components\Pages\Grid.razor" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\BB\BB.csproj" />
  </ItemGroup>

  <ItemGroup>
    <UpToDateCheckInput Remove="Components\Pages\Grid.razor" />
  </ItemGroup>

  <ItemGroup>
    <_ContentIncludedByDefault Remove="Components\Pages\Grid.razor" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Components\Pages\Grid.razor" />
  </ItemGroup>

</Project>
